### ISSUE TITLE
How its works?

### ISSUE THREAD

**Issue by Root-Control** [bojidaryovchev/nest-angular#2]
Hi, i tried to run your repo but i'm getting errors (server isn't running)., can you show me how to run please

**Comment by bojidaryovchev** [comment]
To start the server, you need a mongodb connection because the database.module requires it.. also modify the mongodb connection string in server/config/config.ts.. You need to run npm run build:universal and then npm run watch:server .. I hope that helps, im not home atm so I cant help u any further.. Ill check it out when I get home

**Comment by DrMabuse23** [comment]
what about add a docker file for the database ?

**Comment by bojidaryovchev** [comment]
well maybe further in time
